'type: dependencies': ['upgrades/*', 'upgrade/*', 'dependencies/*']
'type: enhancement': ['feature/*', 'feat/*', 'enhance/*', 'enhancement/*']
'type: bugfix': ['bugfix/*']
'type: hotfix': ['hotfix/*']
'type: chore': ['chore/*', 'maintenance/*', 'maintain/*']
'type: security': ['security/*']
